version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["loop:deps"]
    groups:
      bundler:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["loop:deps"]
    groups:
      github-actions:
        patterns: ["*"]
