# frozen_string_literal: true

# The Index Generator: reads every example's own header comment and
# writes examples/README.md - a catalog that regenerates from the
# files, so it can't rot. Complains about any example missing a run
# line, because an example you can't run is a rumor.
#
#   bundle exec ruby examples/examples_index.rb
#
# Runs offline; rewrites examples/README.md in place.

require_relative "../lib/agentic"

DIR = __dir__

orchestrator = Agentic::PlanOrchestrator.new(concurrency_limit: 8)

files = Dir[File.join(DIR, "*.rb")].sort - [File.join(DIR, File.basename(__FILE__))]

surveys = files.map do |path|
  task = Agentic::Task.new(
    description: File.basename(path),
    agent_spec: {"name" => "Librarian", "instructions" => "catalog the example"},
    payload: path
  )
  orchestrator.add_task(task, agent: ->(t) {
    lines = File.readlines(t.payload, encoding: "UTF-8")
      .reject { |l| l.start_with?("# frozen_string_literal") }
    header = lines.drop_while { |l| !l.start_with?("#") }.take_while { |l| l.start_with?("#") }
    prose = header.map { |l| l.sub(/\A#\s?/, "").rstrip }
    run_line = prose.find { |l| l.strip.start_with?("bundle exec ruby") }

    {
      file: File.basename(t.payload),
      summary: prose.take_while { |l| !l.empty? }.join(" ").squeeze(" "),
      runnable: !run_line.nil?
    }
  })
  task
end

index = Agentic::Task.new(
  description: "write the index",
  agent_spec: {"name" => "Editor", "instructions" => "assemble the catalog"}
)
orchestrator.add_task(index, surveys, agent: ->(t) {
  entries = surveys.map { |s| t.output_of(s) }.sort_by { |e| e[:file] }
  missing_run = entries.reject { |e| e[:runnable] }

  lines = ["# Examples", ""]
  lines << "Every example runs offline: `bundle exec ruby examples/<file>`."
  lines << "This index is generated by `examples_index.rb`; edit the examples,"
  lines << "not this file."
  lines << ""
  lines << "| Example | What it shows |"
  lines << "|---------|---------------|"
  entries.each do |entry|
    summary = entry[:summary][0, 120]
    summary += "..." if entry[:summary].length > 120
    lines << "| `#{entry[:file]}` | #{summary} |"
  end
  {markdown: lines.join("\n") + "\n", count: entries.size, missing_run: missing_run.map { |e| e[:file] }}
})

result = orchestrator.execute_plan
catalog = result.results[index.id].output

File.write(File.join(DIR, "README.md"), catalog[:markdown])

puts "EXAMPLES INDEX: #{catalog[:count]} examples cataloged into examples/README.md"
if catalog[:missing_run].any?
  puts "  examples missing a run line (fix their headers):"
  catalog[:missing_run].each { |f| puts "  - #{f}" }
  exit 1
else
  puts "  every example documents how to run it. catalog is honest."
end
