# frozen_string_literal: true

# The Omakase Scaffold: `rails new` for plans. You bring six lines
# of intent - a name and some steps. The generator brings the menu:
# journaling on, retries configured, concurrency chosen, a runnable
# file with your name on it. Convention over configuration isn't
# about taking choices away; it's about not making you answer forty
# questions before hello-world. And the output is JUST RUBY - a file
# you own, edit, and outgrow. The scaffold is a starting line, not
# a cage.
#
#   bundle exec ruby examples/omakase_scaffold.rb
#
# Runs offline; two recipes are scaffolded, and the generated
# programs are actually RUN - the proof of a generator is its output
# booting, not its template compiling.

require_relative "../lib/agentic"
require "open3"
require "rbconfig"
require "tmpdir"

ROOT = File.expand_path("..", __dir__)

# --- the whole interface: what a recipe author writes ------------------------------
RECIPES = [
  {name: "newsletter_digest",
   steps: [
     {step: "collect articles"},
     {step: "rank by relevance", after: "collect articles"},
     {step: "draft summary", after: "rank by relevance"},
     {step: "format email", after: "draft summary"}
   ]},
  {name: "release_notes",
   steps: [
     {step: "gather merged prs"},
     {step: "gather closed issues"},
     {step: "write highlights", after: ["gather merged prs", "gather closed issues"]}
   ]}
].freeze

# --- the generator: conventions poured around the recipe ---------------------------
def scaffold(recipe, dir)
  vars = recipe[:steps].each_with_index.to_h { |s, i| [s[:step], "task_#{i}"] }
  task_lines = recipe[:steps].map do |s|
    deps = Array(s[:after]).map { |d| vars.fetch(d) }
    <<~RUBY.chomp
      #{vars[s[:step]]} = Agentic::Task.new(description: #{s[:step].inspect}, agent_spec: {"name" => #{s[:step].inspect}, "instructions" => "do it"})
      orchestrator.add_task(#{vars[s[:step]]}, [#{deps.join(", ")}], agent: ->(t) {
        # TODO: replace this stub with your real work for #{s[:step].inspect}
        "#{s[:step]}: done#{" (given: \#{t.previous_output})" if deps.any?}"
      })
    RUBY
  end

  source = <<~RUBY
    # frozen_string_literal: true
    # Generated by omakase_scaffold - and immediately YOURS. Edit freely.
    require "agentic"
    require "tmpdir"

    Agentic.logger.level = :fatal

    # Omakase defaults: a journal (so every run is replayable), a retry
    # policy (transient errors get three chances), a concurrency ceiling
    # (parallel where the graph allows, never a stampede). Disagree with
    # any of it? It's your file now - change it.
    journal = Agentic::ExecutionJournal.new(path: File.join(Dir.tmpdir, "#{recipe[:name]}.jsonl"))
    orchestrator = Agentic::PlanOrchestrator.new(
      concurrency_limit: 4,
      lifecycle_hooks: journal.lifecycle_hooks,
      retry_policy: {max_retries: 3, backoff_base: 0.05, backoff_jitter: :full}
    )

    #{task_lines.join("\n\n").gsub("\n", "\n    ").strip}

    result = orchestrator.execute_plan
    done = result.results.values.count(&:successful?)
    puts "#{recipe[:name]}: \#{result.status}, \#{done}/#{recipe[:steps].size} steps, journal at \#{journal.path}"
    exit(result.status == :completed ? 0 : 1)
  RUBY

  path = File.join(dir, "#{recipe[:name]}.rb")
  File.write(path, source)
  path
end

puts "THE OMAKASE SCAFFOLD (six lines of intent, a running plan back)"
puts

failures = 0
Dir.mktmpdir("omakase") do |dir|
  RECIPES.each do |recipe|
    path = scaffold(recipe, dir)
    lines = File.read(path).lines.size
    out, err, status = Open3.capture3(RbConfig.ruby, "-I", File.join(ROOT, "lib"), path)
    ok = status.success? && out.include?("#{recipe[:name]}: completed")
    failures += 1 unless ok
    puts "  recipe #{recipe[:name].inspect} (#{recipe[:steps].size} steps declared)"
    puts "    generated: #{File.basename(path)} (#{lines} lines you didn't write)"
    puts "    ran it:    #{ok ? out.strip.inspect : "FAILED: #{err.lines.last&.strip}"}"
    puts
  end
end

puts "  the recipe says WHAT (steps and order); the scaffold supplies the"
puts "  HOW everyone forgets until 2am - journaling, retries with jittered"
puts "  backoff, a sane concurrency ceiling. that's omakase: the chef"
puts "  chooses, you eat well, and if you hate the fish you own the"
puts "  kitchen - the generated file is plain Ruby with your name on it,"
puts "  TODOs where your work goes, no framework umbilical. generators"
puts "  are how conventions travel; a convention nobody scaffolds is a"
puts "  convention nobody follows."
exit(failures.zero? ? 0 : 1)
